[
	{
		code: "zOenJ",
		province: "湖南省",
		city: "长沙市",
		url: "/publish/forecast/AHN/changshashi.html",
	},
	{
		code: "NMRKc",
		province: "湖南省",
		city: "常德",
		url: "/publish/forecast/AHN/changde.html",
	},
	{
		code: "pwvLl",
		province: "湖南省",
		city: "长沙黄花",
		url: "/publish/forecast/AHN/changshahuanghua.html",
	},
	{
		code: "cYyyF",
		province: "湖南省",
		city: "郴州",
		url: "/publish/forecast/AHN/chenzhou.html",
	},
	{
		code: "ljEDf",
		province: "湖南省",
		city: "赫山",
		url: "/publish/forecast/AHN/heshan.html",
	},
	{
		code: "ObykY",
		province: "湖南省",
		city: "衡阳",
		url: "/publish/forecast/AHN/hengyang.html",
	},
	{
		code: "pJrqw",
		province: "湖南省",
		city: "怀化",
		url: "/publish/forecast/AHN/huaihua.html",
	},
	{
		code: "gWnFP",
		province: "湖南省",
		city: "吉首",
		url: "/publish/forecast/AHN/jishou.html",
	},
	{
		code: "MhTjl",
		province: "湖南省",
		city: "临武",
		url: "/publish/forecast/AHN/linwu.html",
	},
	{
		code: "ZrEsO",
		province: "湖南省",
		city: "娄底",
		url: "/publish/forecast/AHN/loudi.html",
	},
	{
		code: "gMqBs",
		province: "湖南省",
		city: "南岳",
		url: "/publish/forecast/AHN/nanyue.html",
	},
	{
		code: "UyXiO",
		province: "湖南省",
		city: "桑植",
		url: "/publish/forecast/AHN/sangzhi.html",
	},
	{
		code: "KZYji",
		province: "湖南省",
		city: "邵阳",
		url: "/publish/forecast/AHN/shaoyang.html",
	},
	{
		code: "vcKIn",
		province: "湖南省",
		city: "望城区",
		url: "/publish/forecast/AHN/wangchengqu.html",
	},
	{
		code: "htNqQ",
		province: "湖南省",
		city: "湘江新区",
		url: "/publish/forecast/AHN/xiangjiangxinqu.html",
	},
	{
		code: "tWpqg",
		province: "湖南省",
		city: "湘潭",
		url: "/publish/forecast/AHN/xiangtan.html",
	},
	{
		code: "vXgNI",
		province: "湖南省",
		city: "永州",
		url: "/publish/forecast/AHN/yongzhou.html",
	},
	{
		code: "bwVav",
		province: "湖南省",
		city: "岳阳",
		url: "/publish/forecast/AHN/yueyang.html",
	},
	{
		code: "FOUZo",
		province: "湖南省",
		city: "张家界",
		url: "/publish/forecast/AHN/zhangjiajie.html",
	},
	{
		code: "siHjW",
		province: "湖南省",
		city: "株洲",
		url: "/publish/forecast/AHN/zhuzhou.html",
	},
	{
		code: "RAzQc",
		province: "湖南省",
		city: "沅陵县",
		url: "/publish/forecast/AHN/zuolingxian.html",
	},
	{
		code: "LTAMD",
		province: "湖南省",
		city: "安化",
		url: "/publish/forecast/AHN/anhua.html",
	},
	{
		code: "zMNOt",
		province: "湖南省",
		city: "安仁",
		url: "/publish/forecast/AHN/anren.html",
	},
	{
		code: "ejqKF",
		province: "湖南省",
		city: "安乡",
		url: "/publish/forecast/AHN/anxiang.html",
	},
	{
		code: "aDWvQ",
		province: "湖南省",
		city: "保靖",
		url: "/publish/forecast/AHN/baojing.html",
	},
	{
		code: "cMTxZ",
		province: "湖南省",
		city: "茶陵",
		url: "/publish/forecast/AHN/chaling.html",
	},
	{
		code: "zxmLy",
		province: "湖南省",
		city: "常宁",
		url: "/publish/forecast/AHN/changning.html",
	},
	{
		code: "PSXSM",
		province: "湖南省",
		city: "辰溪",
		url: "/publish/forecast/AHN/chenxi.html",
	},
	{
		code: "OMJHt",
		province: "湖南省",
		city: "城步",
		url: "/publish/forecast/AHN/chengbu.html",
	},
	{
		code: "QhqHU",
		province: "湖南省",
		city: "慈利",
		url: "/publish/forecast/AHN/cili.html",
	},
	{
		code: "anbCP",
		province: "湖南省",
		city: "道县",
		url: "/publish/forecast/AHN/daoxian.html",
	},
	{
		code: "AbmUR",
		province: "湖南省",
		city: "东安",
		url: "/publish/forecast/AHN/dongan.html",
	},
	{
		code: "AWZQQ",
		province: "湖南省",
		city: "洞口",
		url: "/publish/forecast/AHN/dongkou.html",
	},
	{
		code: "HHWQT",
		province: "湖南省",
		city: "凤凰",
		url: "/publish/forecast/AHN/fenghuang.html",
	},
	{
		code: "gpwLy",
		province: "湖南省",
		city: "古丈",
		url: "/publish/forecast/AHN/guzhang.html",
	},
	{
		code: "QaXwQ",
		province: "湖南省",
		city: "桂东",
		url: "/publish/forecast/AHN/guidong.html",
	},
	{
		code: "OMZne",
		province: "湖南省",
		city: "桂阳",
		url: "/publish/forecast/AHN/guiyang.html",
	},
	{
		code: "RvbiI",
		province: "湖南省",
		city: "汉寿",
		url: "/publish/forecast/AHN/hanshou.html",
	},
	{
		code: "qhQyx",
		province: "湖南省",
		city: "衡东",
		url: "/publish/forecast/AHN/hengdong.html",
	},
	{
		code: "GYnJo",
		province: "湖南省",
		city: "衡南",
		url: "/publish/forecast/AHN/hengnan.html",
	},
	{
		code: "inRnV",
		province: "湖南省",
		city: "衡山",
		url: "/publish/forecast/AHN/hengshan.html",
	},
	{
		code: "PMfFu",
		province: "湖南省",
		city: "衡阳县",
		url: "/publish/forecast/AHN/hengyangxian.html",
	},
	{
		code: "dGOEo",
		province: "湖南省",
		city: "洪江",
		url: "/publish/forecast/AHN/hongjiang.html",
	},
	{
		code: "aEkzT",
		province: "湖南省",
		city: "花垣",
		url: "/publish/forecast/AHN/huayuan.html",
	},
	{
		code: "UDpcM",
		province: "湖南省",
		city: "华容",
		url: "/publish/forecast/AHN/huarong.html",
	},
	{
		code: "yzhZl",
		province: "湖南省",
		city: "会同",
		url: "/publish/forecast/AHN/huitong.html",
	},
	{
		code: "CkYws",
		province: "湖南省",
		city: "嘉禾",
		url: "/publish/forecast/AHN/jiahe.html",
	},
	{
		code: "dCAYY",
		province: "湖南省",
		city: "江华",
		url: "/publish/forecast/AHN/jianghua.html",
	},
	{
		code: "XfpWX",
		province: "湖南省",
		city: "江永",
		url: "/publish/forecast/AHN/jiangyong.html",
	},
	{
		code: "WuPCk",
		province: "湖南省",
		city: "靖州",
		url: "/publish/forecast/AHN/jingzhou.html",
	},
	{
		code: "RJaJW",
		province: "湖南省",
		city: "蓝山",
		url: "/publish/forecast/AHN/lanshan.html",
	},
	{
		code: "gUDwK",
		province: "湖南省",
		city: "冷水江",
		url: "/publish/forecast/AHN/lengshuijiang.html",
	},
	{
		code: "YGosR",
		province: "湖南省",
		city: "冷水滩",
		url: "/publish/forecast/AHN/lengshuitan.html",
	},
	{
		code: "MvOMQ",
		province: "湖南省",
		city: "涟源",
		url: "/publish/forecast/AHN/lianyuan.html",
	},
	{
		code: "sabwQ",
		province: "湖南省",
		city: "临湘",
		url: "/publish/forecast/AHN/linxiang.html",
	},
	{
		code: "ZskSj",
		province: "湖南省",
		city: "临澧",
		url: "/publish/forecast/AHN/linzuo.html",
	},
	{
		code: "czHhG",
		province: "湖南省",
		city: "龙山",
		url: "/publish/forecast/AHN/longshan.html",
	},
	{
		code: "ODQnM",
		province: "湖南省",
		city: "隆回",
		url: "/publish/forecast/AHN/longhui.html",
	},
	{
		code: "BByTA",
		province: "湖南省",
		city: "麻阳",
		url: "/publish/forecast/AHN/mayang.html",
	},
	{
		code: "wIetl",
		province: "湖南省",
		city: "南县",
		url: "/publish/forecast/AHN/nanxian.html",
	},
	{
		code: "vRUXM",
		province: "湖南省",
		city: "宁乡",
		url: "/publish/forecast/AHN/ningxiang.html",
	},
	{
		code: "PKMwh",
		province: "湖南省",
		city: "宁远",
		url: "/publish/forecast/AHN/ningyuan.html",
	},
	{
		code: "PdYcV",
		province: "湖南省",
		city: "平江",
		url: "/publish/forecast/AHN/pingjiang.html",
	},
	{
		code: "PHwxt",
		province: "湖南省",
		city: "祁东",
		url: "/publish/forecast/AHN/qidong.html",
	},
	{
		code: "tjUoi",
		province: "湖南省",
		city: "祁阳",
		url: "/publish/forecast/AHN/qiyang.html",
	},
	{
		code: "xyZXg",
		province: "湖南省",
		city: "汝城",
		url: "/publish/forecast/AHN/rucheng.html",
	},
	{
		code: "ctzSw",
		province: "湖南省",
		city: "韶山",
		url: "/publish/forecast/AHN/shaoshan.html",
	},
	{
		code: "qChSW",
		province: "湖南省",
		city: "邵东",
		url: "/publish/forecast/AHN/shaodong.html",
	},
	{
		code: "aFKpi",
		province: "湖南省",
		city: "邵阳县",
		url: "/publish/forecast/AHN/shaoyangxian.html",
	},
	{
		code: "ZGIRj",
		province: "湖南省",
		city: "石门",
		url: "/publish/forecast/AHN/shimen.html",
	},
	{
		code: "gItui",
		province: "湖南省",
		city: "双峰县",
		url: "/publish/forecast/AHN/shuangfengxian.html",
	},
	{
		code: "CcRaN",
		province: "湖南省",
		city: "双牌",
		url: "/publish/forecast/AHN/shuangpai.html",
	},
	{
		code: "WWGiu",
		province: "湖南省",
		city: "绥宁",
		url: "/publish/forecast/AHN/suining.html",
	},
	{
		code: "rJTxk",
		province: "湖南省",
		city: "桃江",
		url: "/publish/forecast/AHN/taojiang.html",
	},
	{
		code: "DYNDO",
		province: "湖南省",
		city: "桃源",
		url: "/publish/forecast/AHN/taoyuan.html",
	},
	{
		code: "uAYSX",
		province: "湖南省",
		city: "通道",
		url: "/publish/forecast/AHN/tongdao.html",
	},
	{
		code: "ZgECL",
		province: "湖南省",
		city: "武冈",
		url: "/publish/forecast/AHN/wugang.html",
	},
	{
		code: "MFued",
		province: "湖南省",
		city: "湘乡",
		url: "/publish/forecast/AHN/xiangxiang.html",
	},
	{
		code: "EJmro",
		province: "湖南省",
		city: "湘阴",
		url: "/publish/forecast/AHN/xiangyin.html",
	},
	{
		code: "FLnON",
		province: "湖南省",
		city: "新化",
		url: "/publish/forecast/AHN/xinhua.html",
	},
	{
		code: "ZOQOg",
		province: "湖南省",
		city: "新晃",
		url: "/publish/forecast/AHN/xinhuang.html",
	},
	{
		code: "eaueH",
		province: "湖南省",
		city: "新宁",
		url: "/publish/forecast/AHN/xinning.html",
	},
	{
		code: "lMPty",
		province: "湖南省",
		city: "新邵",
		url: "/publish/forecast/AHN/xinshao.html",
	},
	{
		code: "qxrUF",
		province: "湖南省",
		city: "新田",
		url: "/publish/forecast/AHN/xintian.html",
	},
	{
		code: "HDZEq",
		province: "湖南省",
		city: "炎陵",
		url: "/publish/forecast/AHN/yanling.html",
	},
	{
		code: "pbfyp",
		province: "湖南省",
		city: "宜章",
		url: "/publish/forecast/AHN/yizhang.html",
	},
	{
		code: "LLJXv",
		province: "湖南省",
		city: "永顺",
		url: "/publish/forecast/AHN/yongshun.html",
	},
	{
		code: "rwydQ",
		province: "湖南省",
		city: "永兴",
		url: "/publish/forecast/AHN/yongxing.html",
	},
	{
		code: "shWKT",
		province: "湖南省",
		city: "岳阳县",
		url: "/publish/forecast/AHN/yueyangxian.html",
	},
	{
		code: "UbStp",
		province: "湖南省",
		city: "资兴",
		url: "/publish/forecast/AHN/zixing.html",
	},
	{
		code: "UUaLX",
		province: "湖南省",
		city: "攸县",
		url: "/publish/forecast/AHN/zuoxian2.html",
	},
	{
		code: "robJO",
		province: "湖南省",
		city: "芷江",
		url: "/publish/forecast/AHN/zuojiang2.html",
	},
	{
		code: "xFxiZ",
		province: "湖南省",
		city: "沅江",
		url: "/publish/forecast/AHN/zuojiang1.html",
	},
	{
		code: "AlxsQ",
		province: "湖南省",
		city: "汨罗",
		url: "/publish/forecast/AHN/zuoluo.html",
	},
	{
		code: "XsVCU",
		province: "湖南省",
		city: "泸溪",
		url: "/publish/forecast/AHN/zuoxi.html",
	},
	{
		code: "eprZJ",
		province: "湖南省",
		city: "浏阳",
		url: "/publish/forecast/AHN/zuoyang1.html",
	},
	{
		code: "ltdEd",
		province: "湖南省",
		city: "溆浦",
		url: "/publish/forecast/AHN/zuopu.html",
	},
	{
		code: "VdxXV",
		province: "湖南省",
		city: "澧县",
		url: "/publish/forecast/AHN/zuoxian1.html",
	},
	{
		code: "fzyGq",
		province: "湖南省",
		city: "耒阳",
		url: "/publish/forecast/AHN/zuoyang2.html",
	},
	{
		code: "aSeFW",
		province: "湖南省",
		city: "醴陵",
		url: "/publish/forecast/AHN/zuoling.html",
	},
];
