function Component() {
	const bbb = [
		{
			code: "uJQqI",
			province: "河北省",
			city: "石家庄",
			url: "/publish/forecast/AHE/shijiazhuang.html",
		},
		{
			code: "FaykR",
			province: "河北省",
			city: "保定",
			url: "/publish/forecast/AHE/baoding.html",
		},
		{
			code: "mHkdW",
			province: "河北省",
			city: "沧州",
			url: "/publish/forecast/AHE/cangzhou.html",
		},
		{
			code: "oWYwK",
			province: "河北省",
			city: "承德",
			url: "/publish/forecast/AHE/chengde.html",
		},
		{
			code: "AwDQd",
			province: "河北省",
			city: "邯郸",
			url: "/publish/forecast/AHE/handan.html",
		},
		{
			code: "Jiheq",
			province: "河北省",
			city: "衡水",
			url: "/publish/forecast/AHE/hengshui.html",
		},
		{
			code: "gXmTp",
			province: "河北省",
			city: "廊坊",
			url: "/publish/forecast/AHE/langfang.html",
		},
		{
			code: "rlWKm",
			province: "河北省",
			city: "鹿泉",
			url: "/publish/forecast/AHE/luquan.html",
		},
		{
			code: "SBrmr",
			province: "河北省",
			city: "秦皇岛",
			url: "/publish/forecast/AHE/qinhuangdao.html",
		},
		{
			code: "nBdMW",
			province: "河北省",
			city: "任丘",
			url: "/publish/forecast/AHE/renqiu.html",
		},
		{
			code: "iqimR",
			province: "河北省",
			city: "容城",
			url: "/publish/forecast/AHE/rongcheng.html",
		},
		{
			code: "aCRJR",
			province: "河北省",
			city: "唐山",
			url: "/publish/forecast/AHE/tangshan.html",
		},
		{
			code: "WgyJx",
			province: "河北省",
			city: "邢台",
			url: "/publish/forecast/AHE/xingtai.html",
		},
		{
			code: "AXmqR",
			province: "河北省",
			city: "张家口",
			url: "/publish/forecast/AHE/zhangjiakou.html",
		},
		{
			code: "vceHS",
			province: "河北省",
			city: "安国",
			url: "/publish/forecast/AHE/anguo.html",
		},
		{
			code: "yeGPa",
			province: "河北省",
			city: "安平",
			url: "/publish/forecast/AHE/anping.html",
		},
		{
			code: "UujiJ",
			province: "河北省",
			city: "安新",
			url: "/publish/forecast/AHE/anxin.html",
		},
		{
			code: "kgrJx",
			province: "河北省",
			city: "霸州",
			url: "/publish/forecast/AHE/bazhou.html",
		},
		{
			code: "dVXww",
			province: "河北省",
			city: "柏乡",
			url: "/publish/forecast/AHE/baixiang.html",
		},
		{
			code: "hIkaB",
			province: "河北省",
			city: "渤海新区黄骅",
			url: "/publish/forecast/AHE/bohaixinquhuangzuo.html",
		},
		{
			code: "pSXjM",
			province: "河北省",
			city: "泊头",
			url: "/publish/forecast/AHE/botou.html",
		},
		{
			code: "wrjjn",
			province: "河北省",
			city: "曹妃甸",
			url: "/publish/forecast/AHE/caozuodian.html",
		},
		{
			code: "qXsSz",
			province: "河北省",
			city: "曹妃甸零公里",
			url: "/publish/forecast/AHE/caozuodianlinggongli.html",
		},
		{
			code: "vTGXA",
			province: "河北省",
			city: "昌黎",
			url: "/publish/forecast/AHE/changli.html",
		},
		{
			code: "HMSVy",
			province: "河北省",
			city: "成安",
			url: "/publish/forecast/AHE/chengan.html",
		},
		{
			code: "WYnNt",
			province: "河北省",
			city: "承德县",
			url: "/publish/forecast/AHE/chengdexian.html",
		},
		{
			code: "yeGWo",
			province: "河北省",
			city: "赤城",
			url: "/publish/forecast/AHE/chicheng.html",
		},
		{
			code: "pOnxu",
			province: "河北省",
			city: "崇礼",
			url: "/publish/forecast/AHE/chongli.html",
		},
		{
			code: "vQqbv",
			province: "河北省",
			city: "磁县",
			url: "/publish/forecast/AHE/cixian.html",
		},
		{
			code: "VzbqG",
			province: "河北省",
			city: "大厂",
			url: "/publish/forecast/AHE/dachang.html",
		},
		{
			code: "qitbz",
			province: "河北省",
			city: "大城",
			url: "/publish/forecast/AHE/dacheng.html",
		},
		{
			code: "ylLRu",
			province: "河北省",
			city: "大名",
			url: "/publish/forecast/AHE/daming.html",
		},
		{
			code: "EXTBR",
			province: "河北省",
			city: "定州",
			url: "/publish/forecast/AHE/dingzhou.html",
		},
		{
			code: "BRTol",
			province: "河北省",
			city: "东光",
			url: "/publish/forecast/AHE/dongguang.html",
		},
		{
			code: "JnWfX",
			province: "河北省",
			city: "肥乡",
			url: "/publish/forecast/AHE/feixiang.html",
		},
		{
			code: "dLkgL",
			province: "河北省",
			city: "丰南",
			url: "/publish/forecast/AHE/fengnan.html",
		},
		{
			code: "MnxTS",
			province: "河北省",
			city: "丰宁",
			url: "/publish/forecast/AHE/fengning.html",
		},
		{
			code: "Aaghn",
			province: "河北省",
			city: "丰润",
			url: "/publish/forecast/AHE/fengrun.html",
		},
		{
			code: "eRyds",
			province: "河北省",
			city: "峰峰",
			url: "/publish/forecast/AHE/fengfeng.html",
		},
		{
			code: "TAGXi",
			province: "河北省",
			city: "抚宁",
			url: "/publish/forecast/AHE/funing.html",
		},
		{
			code: "lOwCw",
			province: "河北省",
			city: "阜城",
			url: "/publish/forecast/AHE/fucheng.html",
		},
		{
			code: "XELos",
			province: "河北省",
			city: "阜平",
			url: "/publish/forecast/AHE/fuping.html",
		},
		{
			code: "nSuxQ",
			province: "河北省",
			city: "高碑店",
			url: "/publish/forecast/AHE/gaobeidian.html",
		},
		{
			code: "QIPjL",
			province: "河北省",
			city: "高阳",
			url: "/publish/forecast/AHE/gaoyang.html",
		},
		{
			code: "Slmxc",
			province: "河北省",
			city: "高邑",
			url: "/publish/forecast/AHE/gaoyi.html",
		},
		{
			code: "bsXrE",
			province: "河北省",
			city: "沽源",
			url: "/publish/forecast/AHE/guyuan.html",
		},
		{
			code: "eRflS",
			province: "河北省",
			city: "故城",
			url: "/publish/forecast/AHE/gucheng.html",
		},
		{
			code: "RSzaV",
			province: "河北省",
			city: "固安",
			url: "/publish/forecast/AHE/guan.html",
		},
		{
			code: "cAOkd",
			province: "河北省",
			city: "馆陶",
			url: "/publish/forecast/AHE/guantao.html",
		},
		{
			code: "fQMyR",
			province: "河北省",
			city: "广平",
			url: "/publish/forecast/AHE/guangping.html",
		},
		{
			code: "mKRmY",
			province: "河北省",
			city: "广宗",
			url: "/publish/forecast/AHE/guangzong.html",
		},
		{
			code: "kqMHD",
			province: "河北省",
			city: "海兴",
			url: "/publish/forecast/AHE/haixing.html",
		},
		{
			code: "pWduF",
			province: "河北省",
			city: "河间",
			url: "/publish/forecast/AHE/hejian.html",
		},
		{
			code: "GKAfR",
			province: "河北省",
			city: "怀安",
			url: "/publish/forecast/AHE/huaian.html",
		},
		{
			code: "TNNEz",
			province: "河北省",
			city: "怀来",
			url: "/publish/forecast/AHE/huailai.html",
		},
		{
			code: "AGkyS",
			province: "河北省",
			city: "鸡泽",
			url: "/publish/forecast/AHE/jize.html",
		},
		{
			code: "qllqX",
			province: "河北省",
			city: "冀州",
			url: "/publish/forecast/AHE/jizhou.html",
		},
		{
			code: "vGudX",
			province: "河北省",
			city: "晋州",
			url: "/publish/forecast/AHE/jinzhou.html",
		},
		{
			code: "PxsDy",
			province: "河北省",
			city: "井陉",
			url: "/publish/forecast/AHE/jingzuo.html",
		},
		{
			code: "gMmSA",
			province: "河北省",
			city: "景县",
			url: "/publish/forecast/AHE/jingxian.html",
		},
		{
			code: "XXUYp",
			province: "河北省",
			city: "巨鹿",
			url: "/publish/forecast/AHE/julu.html",
		},
		{
			code: "KcroZ",
			province: "河北省",
			city: "康保",
			url: "/publish/forecast/AHE/kangbao.html",
		},
		{
			code: "aQZks",
			province: "河北省",
			city: "宽城",
			url: "/publish/forecast/AHE/kuancheng.html",
		},
		{
			code: "BygfA",
			province: "河北省",
			city: "乐亭",
			url: "/publish/forecast/AHE/leting.html",
		},
		{
			code: "tBOjo",
			province: "河北省",
			city: "临城",
			url: "/publish/forecast/AHE/lincheng.html",
		},
		{
			code: "quDcn",
			province: "河北省",
			city: "临西",
			url: "/publish/forecast/AHE/linxi.html",
		},
		{
			code: "iStnu",
			province: "河北省",
			city: "临漳",
			url: "/publish/forecast/AHE/linzhang.html",
		},
		{
			code: "TynGR",
			province: "河北省",
			city: "灵寿",
			url: "/publish/forecast/AHE/lingshou.html",
		},
		{
			code: "KkHVu",
			province: "河北省",
			city: "隆化",
			url: "/publish/forecast/AHE/longhua.html",
		},
		{
			code: "CoRNr",
			province: "河北省",
			city: "隆尧",
			url: "/publish/forecast/AHE/longyao.html",
		},
		{
			code: "uszcX",
			province: "河北省",
			city: "卢龙",
			url: "/publish/forecast/AHE/lulong.html",
		},
		{
			code: "RlsNU",
			province: "河北省",
			city: "滦南",
			url: "/publish/forecast/AHE/luannan.html",
		},
		{
			code: "gPeaq",
			province: "河北省",
			city: "滦平",
			url: "/publish/forecast/AHE/luanping.html",
		},
		{
			code: "zbjeL",
			province: "河北省",
			city: "滦州",
			url: "/publish/forecast/AHE/luanzhou.html",
		},
		{
			code: "zHLty",
			province: "河北省",
			city: "满城",
			url: "/publish/forecast/AHE/mancheng.html",
		},
		{
			code: "gKfij",
			province: "河北省",
			city: "孟村",
			url: "/publish/forecast/AHE/mengcun.html",
		},
		{
			code: "QDdHX",
			province: "河北省",
			city: "南宫",
			url: "/publish/forecast/AHE/nangong.html",
		},
		{
			code: "HjWcO",
			province: "河北省",
			city: "南和",
			url: "/publish/forecast/AHE/nanhe.html",
		},
		{
			code: "EtUJU",
			province: "河北省",
			city: "南皮",
			url: "/publish/forecast/AHE/nanpi.html",
		},
		{
			code: "tbLfc",
			province: "河北省",
			city: "内丘",
			url: "/publish/forecast/AHE/neiqiu.html",
		},
		{
			code: "QwGch",
			province: "河北省",
			city: "宁晋",
			url: "/publish/forecast/AHE/ningjin.html",
		},
		{
			code: "rhIky",
			province: "河北省",
			city: "平泉",
			url: "/publish/forecast/AHE/pingquan.html",
		},
		{
			code: "lzuFh",
			province: "河北省",
			city: "平山",
			url: "/publish/forecast/AHE/pingshan.html",
		},
		{
			code: "cOXrB",
			province: "河北省",
			city: "平乡",
			url: "/publish/forecast/AHE/pingxiang.html",
		},
		{
			code: "qUXcf",
			province: "河北省",
			city: "迁安",
			url: "/publish/forecast/AHE/qianan.html",
		},
		{
			code: "qvzeN",
			province: "河北省",
			city: "迁西",
			url: "/publish/forecast/AHE/qianxi.html",
		},
		{
			code: "DlwUH",
			province: "河北省",
			city: "青龙",
			url: "/publish/forecast/AHE/qinglong.html",
		},
		{
			code: "tspDy",
			province: "河北省",
			city: "青县",
			url: "/publish/forecast/AHE/qingxian.html",
		},
		{
			code: "zUBhk",
			province: "河北省",
			city: "清河",
			url: "/publish/forecast/AHE/qinghe.html",
		},
		{
			code: "uEdAG",
			province: "河北省",
			city: "邱县",
			url: "/publish/forecast/AHE/qiuxian.html",
		},
		{
			code: "KVJiP",
			province: "河北省",
			city: "曲阳",
			url: "/publish/forecast/AHE/quyang.html",
		},
		{
			code: "fAOhd",
			province: "河北省",
			city: "曲周",
			url: "/publish/forecast/AHE/quzhou.html",
		},
		{
			code: "VyOJb",
			province: "河北省",
			city: "饶阳",
			url: "/publish/forecast/AHE/raoyang.html",
		},
		{
			code: "zkSoL",
			province: "河北省",
			city: "任泽",
			url: "/publish/forecast/AHE/renze.html",
		},
		{
			code: "qSdEK",
			province: "河北省",
			city: "三河",
			url: "/publish/forecast/AHE/sanhe.html",
		},
		{
			code: "DPtSW",
			province: "河北省",
			city: "沙河",
			url: "/publish/forecast/AHE/shahe.html",
		},
		{
			code: "BukSn",
			province: "河北省",
			city: "尚义",
			url: "/publish/forecast/AHE/shangyi.html",
		},
		{
			code: "YueHa",
			province: "河北省",
			city: "涉县",
			url: "/publish/forecast/AHE/shexian.html",
		},
		{
			code: "vGtXb",
			province: "河北省",
			city: "深泽",
			url: "/publish/forecast/AHE/shenze.html",
		},
		{
			code: "upNrO",
			province: "河北省",
			city: "深州",
			url: "/publish/forecast/AHE/shenzhou.html",
		},
		{
			code: "AFgnu",
			province: "河北省",
			city: "顺平",
			url: "/publish/forecast/AHE/shunping.html",
		},
		{
			code: "gZrxg",
			province: "河北省",
			city: "肃宁",
			url: "/publish/forecast/AHE/suning.html",
		},
		{
			code: "IIPwa",
			province: "河北省",
			city: "唐县",
			url: "/publish/forecast/AHE/tangxian.html",
		},
		{
			code: "nXeQi",
			province: "河北省",
			city: "万全",
			url: "/publish/forecast/AHE/wanquan.html",
		},
		{
			code: "uvaeY",
			province: "河北省",
			city: "望都",
			url: "/publish/forecast/AHE/wangdu.html",
		},
		{
			code: "LzLae",
			province: "河北省",
			city: "威县",
			url: "/publish/forecast/AHE/weixian3.html",
		},
		{
			code: "hbBle",
			province: "河北省",
			city: "围场",
			url: "/publish/forecast/AHE/weichang.html",
		},
		{
			code: "YbKUt",
			province: "河北省",
			city: "蔚县",
			url: "/publish/forecast/AHE/weixian1.html",
		},
		{
			code: "JdkhE",
			province: "河北省",
			city: "魏县",
			url: "/publish/forecast/AHE/weixian2.html",
		},
		{
			code: "TKCta",
			province: "河北省",
			city: "文安",
			url: "/publish/forecast/AHE/wenan.html",
		},
		{
			code: "YGoOp",
			province: "河北省",
			city: "无极",
			url: "/publish/forecast/AHE/wuji.html",
		},
		{
			code: "MHgRX",
			province: "河北省",
			city: "吴桥",
			url: "/publish/forecast/AHE/wuqiao.html",
		},
		{
			code: "FwHWv",
			province: "河北省",
			city: "武安",
			url: "/publish/forecast/AHE/wuan.html",
		},
		{
			code: "KZDpU",
			province: "河北省",
			city: "武强",
			url: "/publish/forecast/AHE/wuqiang.html",
		},
		{
			code: "NiqiA",
			province: "河北省",
			city: "武邑",
			url: "/publish/forecast/AHE/wuyi.html",
		},
		{
			code: "KCdLb",
			province: "河北省",
			city: "献县",
			url: "/publish/forecast/AHE/xianxian.html",
		},
		{
			code: "xWfUk",
			province: "河北省",
			city: "香河",
			url: "/publish/forecast/AHE/xianghe.html",
		},
		{
			code: "HdwIC",
			province: "河北省",
			city: "辛集",
			url: "/publish/forecast/AHE/xinji.html",
		},
		{
			code: "YGLDG",
			province: "河北省",
			city: "新河",
			url: "/publish/forecast/AHE/xinhe.html",
		},
		{
			code: "xNnEo",
			province: "河北省",
			city: "新乐",
			url: "/publish/forecast/AHE/xinle.html",
		},
		{
			code: "qWokG",
			province: "河北省",
			city: "兴隆",
			url: "/publish/forecast/AHE/xinglong.html",
		},
		{
			code: "rZAWC",
			province: "河北省",
			city: "行唐",
			url: "/publish/forecast/AHE/xingtang.html",
		},
		{
			code: "FTACx",
			province: "河北省",
			city: "雄县",
			url: "/publish/forecast/AHE/xiongxian.html",
		},
		{
			code: "VNsra",
			province: "河北省",
			city: "徐水",
			url: "/publish/forecast/AHE/xushui.html",
		},
		{
			code: "bLxvu",
			province: "河北省",
			city: "宣化",
			url: "/publish/forecast/AHE/xuanhua.html",
		},
		{
			code: "lqiAy",
			province: "河北省",
			city: "盐山",
			url: "/publish/forecast/AHE/yanshan.html",
		},
		{
			code: "daicd",
			province: "河北省",
			city: "阳原",
			url: "/publish/forecast/AHE/yangyuan.html",
		},
		{
			code: "mnilQ",
			province: "河北省",
			city: "易县",
			url: "/publish/forecast/AHE/yixian.html",
		},
		{
			code: "bJQcD",
			province: "河北省",
			city: "永年",
			url: "/publish/forecast/AHE/yongnian.html",
		},
		{
			code: "DaCoA",
			province: "河北省",
			city: "永清",
			url: "/publish/forecast/AHE/yongqing.html",
		},
		{
			code: "SHtYc",
			province: "河北省",
			city: "玉田",
			url: "/publish/forecast/AHE/yutian.html",
		},
		{
			code: "XHFGV",
			province: "河北省",
			city: "元氏",
			url: "/publish/forecast/AHE/yuanshi.html",
		},
		{
			code: "mEbhg",
			province: "河北省",
			city: "赞皇",
			url: "/publish/forecast/AHE/zanhuang.html",
		},
		{
			code: "PZHKx",
			province: "河北省",
			city: "枣强",
			url: "/publish/forecast/AHE/zaoqiang.html",
		},
		{
			code: "Ykfmn",
			province: "河北省",
			city: "张北",
			url: "/publish/forecast/AHE/zhangbei.html",
		},
		{
			code: "yXSFQ",
			province: "河北省",
			city: "赵县",
			url: "/publish/forecast/AHE/zhaoxian.html",
		},
		{
			code: "sENtA",
			province: "河北省",
			city: "正定",
			url: "/publish/forecast/AHE/zhengding.html",
		},
		{
			code: "Bcxig",
			province: "河北省",
			city: "遵化",
			url: "/publish/forecast/AHE/zunhua.html",
		},
		{
			code: "BMDXb",
			province: "河北省",
			city: "藁城",
			url: "/publish/forecast/AHE/zuocheng1.html",
		},
		{
			code: "ZdmWW",
			province: "河北省",
			city: "涞源",
			url: "/publish/forecast/AHE/zuoyuan.html",
		},
		{
			code: "oqgGH",
			province: "河北省",
			city: "涿鹿",
			url: "/publish/forecast/AHE/zuolu.html",
		},
		{
			code: "BGCup",
			province: "河北省",
			city: "涿州",
			url: "/publish/forecast/AHE/zuozhou.html",
		},
		{
			code: "vPoEm",
			province: "河北省",
			city: "栾城",
			url: "/publish/forecast/AHE/zuocheng2.html",
		},
		{
			code: "yYUQU",
			province: "河北省",
			city: "蠡县",
			url: "/publish/forecast/AHE/zuoxian.html",
		},
	];

	// 去除bbb中的url属性
	const ccc = bbb.map((item) => {
		return {
			code: item.code, // 需要显式定义键和值
			province: item.province,
			city: item.city,
		};
	});
	console.log("%c Line:750 🥪 ccc", "color:#42b983", ccc);
	return <div className="">11</div>;
}

export default Component;
